# This is the definitive configuration for deploying to Cloudflare.

name = "Riot Drill"
main = "worker/index.ts" # Points to our Hono backend entrypoint.
compatibility_date = "2024-07-15"

# This flag is required because our dependencies use Node.js APIs.
compatibility_flags = ["nodejs_compat_v2"]

# This section tells Wrangler to upload the contents of the "./dist" directory,
# which is where Vite builds our React frontend.
[site]
bucket = "./dist"
