# This configuration is for deploying a Worker that also serves a static site.

name = "riot-drill"
main = "worker/index.ts" # Path to our Hono backend worker
compatibility_date = "2024-07-15"

# This flag is required because our dependencies use Node.js APIs.
compatibility_flags = ["nodejs_compat_v2"]

# This section tells Wrangler where to find our built frontend assets.
[site]
bucket = "./dist"
