# This is the standard configuration file for Cloudflare Workers.
# It tells Wrangler and the Vite plugin how to build and deploy your application.

name = "apex-agent"
main = "worker/index.ts" # Points to our Hono backend entrypoint.
compatibility_date = "2024-07-15"

# Explicitly enabling the v2 Node.js compatibility mode, which is required
# because our dependencies use Node.js APIs.
compatibility_flags = ["nodejs_compat_v2"]
