name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # Or whatever your main branch is called

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          # These secrets are the ones you configured in your GitHub repository settings
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # This must match the 'name' in your wrangler.toml file
          projectName: "riot-drill"
          # This is the directory that Vite builds your frontend to
          directory: "./dist/client"
          # This tells the action to use the project's version of wrangler
          wranglerVersion: '3'
